### ISSUE TITLE
Video URL scraping fail for vk.com links

### ISSUE THREAD

**Issue by itpowerse** [kokangit/xbmc-swefilmer#10]
Hi and thanks for a super add-on to xbmc!

Using xbmc-swefilmer 1.4 on XBMC 13.2 ATV2 and trying different movie links with vk.com links fail to render using script. Below is an example for a movie and the issue seems to simply be that the prefix http: is missing from the scraped video URL.

<pre><code>
23:16:36 T:160686080  NOTICE: -->Python Interpreter Initialized<--
23:16:37 T:160686080  NOTICE: get_url (video.html): http://www.swefilmer.com/colt-45-2014/colt-45-2014-video_ca5e85d08.html
23:16:39 T:160686080  NOTICE: scrape_video: description=['Vincent Mil\xc3\xa8s \xc3\xa4r n\xc3\xb6jd med sitt jobb som vapensmed och\nskjutvapeninstrukt\xc3\xb6r hos den franska polisen, men b\xc3\xb6rjar tappa\nkontrollen p\xc3\xa5 sitt liv n\xc3\xa4r han m\xc3\xb6ter Milo Cardena, en polis som\ninvolverar Vincent i en serie av v\xc3\xa5ldsamma v\xc3\xa4pnade r\xc3\xa5n.']
23:16:39 T:160686080  NOTICE: scrape_video: img=['http://i57.tinypic.com/2ivnocj.jpg']
23:16:39 T:160686080  NOTICE: found garbled player
23:16:39 T:160686080  NOTICE: scrape_video: html=<iframe scrolling="no" src="http://eo8c9j1bgl.swefilmer.info/video_ext.php?oid=234031908&id=171110834&hash=77847b63335023b9" width="500" height="370" frameborder="0"></iframe>
23:16:39 T:160686080  NOTICE: scrape_video: url=http://eo8c9j1bgl.swefilmer.info/video_ext.php?oid=234031908&id=171110834&hash=77847b63335023b9
23:16:39 T:160686080  NOTICE: get_url (document.html): http://eo8c9j1bgl.swefilmer.info/video_ext.php?oid=234031908&id=171110834&hash=77847b63335023b9
23:16:39 T:160686080  NOTICE: scrape_video: url= //vk.com/video_ext.php?oid=234031908&id=171110834&hash=77847b63335023b9
23:16:39 T:160686080  NOTICE: get_url (iframe.html): //vk.com/video_ext.php?oid=234031908&id=171110834&hash=77847b63335023b9
23:16:39 T:160686080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: //vk.com/video_ext.php?oid=234031908&id=171110834&hash=77847b63335023b9
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/XBMC/addons/xbmc-swefilmer-1.4/default.py", line 13, in <module>
                                                navigation.dispatch()
                                              File "/var/mobile/Library/Preferences/XBMC/addons/xbmc-swefilmer-1.4/navigation.py", line 238, in dispatch
                                                ret = self.video()
                                              File "/var/mobile/Library/Preferences/XBMC/addons/xbmc-swefilmer-1.4/navigation.py", line 181, in video
                                                result = self.swefilmer.scrape_video(html)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/xbmc-swefilmer-1.4/swefilmer.py", line 253, in scrape_video
                                                html = self.get_url(iframe[0], 'iframe.html')
                                              File "/var/mobile/Library/Preferences/XBMC/addons/xbmc-swefilmer-1.4/swefilmer.py", line 58, in get_url
                                                response = urllib2.urlopen(req, data)
                                              File "/Users/Shared/jenkins/workspace/XBMC-IOS-ATV2/tools/depends/xbmc-depends/iphoneos4.2_armv7-target/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/Users/Shared/jenkins/workspace/XBMC-IOS-ATV2/tools/depends/xbmc-depends/iphoneos4.2_armv7-target/lib/python2.6/urllib2.py", line 383, in open
                                              File "/Users/Shared/jenkins/workspace/XBMC-IOS-ATV2/tools/depends/xbmc-depends/iphoneos4.2_armv7-target/lib/python2.6/urllib2.py", line 244, in get_type
                                            ValueError: unknown url type: //vk.com/video_ext.php?oid=234031908&id=171110834&hash=77847b63335023b9
                                            -->End of Python script error report<--
23:16:39 T:117436416   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.swefilmer/?action=video&url=http%3A%2F%2Fwww.swefilmer.com%2Fcolt-45-2014%2Fcolt-45-2014-video_ca5e85d08.html&logged_in=True]
</pre></code>

**Comment by kokangit** [comment]
Thanks for the excellent bug report. I have now released v1.5 with a fix for this problem.
